version: "3.9"
services:
  postgres:
    container_name: postgres_lienanimal
    image: postgres:latest
    working_dir: /app
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgres_lienanimal:/var/lib/postgresql/data

volumes:
  postgres_lienanimal:
